### ISSUE TITLE
Error on utilities.js

### ISSUE THREAD

**Issue by DavidOFenley** [albert-sun/bestbuy-queue-automation#2]
There is an error when trying to save the utilities.js script.   
I get the error   Invalid Userscript.

Is this script a work in progress or do we need it for one of the others to run?

**Comment by albert-sun** [comment]
The utilities script is not a separate Tampermonkey script but rather a utilities script as the name suggests. It is automatically imported by the other scripts (only script_cart.js currently) via the @require metadata header at the top of the script. You don't have to worry about it as Tampermonkey / Greasemonkey does the importing automatically.

**Comment by DavidOFenley** [comment]
Any way you and I could chat directly?  I was wanting to ask a couple of
questions about the script to see if I was running it correctly. Also I
wanted to see if you would be interested in building me one for a different
site.

**Comment by albert-sun** [comment]
You can contact me via Discord (contact information is on the README). Might be down to make one for a different site if you wanna talk over the details in DM.
