### ISSUE TITLE
Sound not playing

### ISSUE THREAD

**Issue by hypercoyote** [albert-sun/bestbuy-queue-automation#3]
It seems the sound is not playing when an item is added to the cart and a new window is opened.  I thought maybe I missed it, but I inserted an `audio.play();` line right after the audio object is created to play it immediately and it doesn't play anything.  I tried another mp3 location and tried to BASE64 encode it within the script and still nothing.

It could be something else, but I really dunno what else to try.

**Comment by hypercoyote** [comment]
Smh, never mind.  I was using Incognito windows and apparently they decided to block the audio 🤦‍♂️

**Comment by Maveric0623** [comment]
> Smh, never mind. I was using Incognito windows and apparently they decided to block the audio 🤦‍♂️

How do you unblock the audio in incognito mode?

**Comment by hypercoyote** [comment]
> 
> 
> > Smh, never mind. I was using Incognito windows and apparently they decided to block the audio 🤦‍♂️
> 
> How do you unblock the audio in incognito mode?

To the left of your address bar, in Firefox.  There's options there on what to allow on the site.  But unblock it in normal mode so it will save the change.  If you unblock it in incognito mode, it'll just revert.

**Comment by Maveric0623** [comment]
> > > Smh, never mind. I was using Incognito windows and apparently they decided to block the audio 🤦‍♂️
> > 
> > 
> > How do you unblock the audio in incognito mode?
> 
> To the left of your address bar, in Firefox. There's options there on what to allow on the site. But unblock it in normal mode so it will save the change. If you unblock it in incognito mode, it'll just revert.

Thanks for the info. I'm using Chrome and unfortunately I can't get the audio to work even after unblocking it like you suggested for Firefox.

**Comment by albert-sun** [comment]
Hi, turns out it might be a hotlinking issue from the website. I'm in the process of porting everything over to https://github.com/albert-sun/tamper-scripts, but if you don't want to update you can replace the audio link with https://raw.githubusercontent.com/albert-sun/bestbuy-queue-automation/main/bestbuy-cart/notification.mp3.

**Comment by hypercoyote** [comment]
Why not just embed an audio file in the script using Base64?  It's not that large and would cut out a point of failure.

**Comment by Maveric0623** [comment]
> Hi, turns out it might be a hotlinking issue from the website. I'm in the process of porting everything over to https://github.com/albert-sun/tamper-scripts, but if you don't want to update you can replace the audio link with https://raw.githubusercontent.com/albert-sun/bestbuy-queue-automation/main/bestbuy-cart/notification.mp3.

So line 95 should be: "const audio = new Audio("https://raw.githubusercontent.com/albert-sun/bestbuy-queue-automation/main/bestbuy-cart/notification.mp3");" ?

Thanks!

**Comment by hypercoyote** [comment]
> 
> 
> > Hi, turns out it might be a hotlinking issue from the website. I'm in the process of porting everything over to https://github.com/albert-sun/tamper-scripts, but if you don't want to update you can replace the audio link with https://raw.githubusercontent.com/albert-sun/bestbuy-queue-automation/main/bestbuy-cart/notification.mp3.
> 
> So line 95 should be: "const audio = new Audio("https://raw.githubusercontent.com/albert-sun/bestbuy-queue-automation/main/bestbuy-cart/notification.mp3");" ?
> 
> Thanks!

Yes, that looks correct.  You can also encode an MP3 into Base64 and insert it directly into the script like this:

`const audio = new Audio("data:audio/mp3;base64,BASE64_STRING_HERE");`
       
The base64 string will be very long, but it'll be in the script and you don't have to worry about the site breaking the link anymore.

You can upload a file and convert it to Base64 here:  https://base64.guru/converter/encode/file

**Comment by Maveric0623** [comment]
> const audio = new Audio("data:audio/mp3;base64,BASE64_STRING_HERE");

That seems to work. Thanks so much all!
